name: Create PR on Release

# Triggered when a new version is released publicly
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - name: Checkout
        id: checkout
        # https://github.com/actions/checkout/releases/tag/v4.1.6
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Create Pull Request
        id: create_pull
        run: |
          # Building the PR Data
          # The assignee will be the actor that published the release
          PR_DATA=$(gh pr create \
            --title "chore: [${{ github.ref_name }}] Merge release into master" \
            --body "Automated PR to merge `release` branch into `master` based on release event." \
            --base "master" \
            --head "release" \
            --assignee "@me")
          pr_number=$(echo $PR_URL | grep -oP '/pull/\K\d+')
          echo "pr_number=pr_number" >> $GITHUB_OUTPUT
          echo "Merge PR data: $PR_DATA"

      - name: Associate PR with project
        env:
          PROJECT_NUMBER: 1
          ORG_NAME: TulioMirPoCs
          PR_NUMBER: ${{ steps.create_pull.outputs.pr_number }}
        run: |
          gh project item-create \
            --project $PROJECT_NUMBER \
            --content-id $(gh pr view $PR_NUMBER --json id -q .id) \
            --body "Associating PR #$PR_NUMBER with project"
